2024-05-16 22:46:09,523 INFO    MainThread:20164 [wandb_setup.py:_flush():76] Current SDK version is 0.17.0
2024-05-16 22:46:09,523 INFO    MainThread:20164 [wandb_setup.py:_flush():76] Configure stats pid to 20164
2024-05-16 22:46:09,524 INFO    MainThread:20164 [wandb_setup.py:_flush():76] Loading settings from C:\Users\zimmer\.config\wandb\settings
2024-05-16 22:46:09,524 INFO    MainThread:20164 [wandb_setup.py:_flush():76] Loading settings from c:\Users\zimmer\Desktop\AVANTECH\deep-sign\Training\wandb\settings
2024-05-16 22:46:09,524 INFO    MainThread:20164 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-05-16 22:46:09,524 INFO    MainThread:20164 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-05-16 22:46:09,525 INFO    MainThread:20164 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-05-16 22:46:09,525 INFO    MainThread:20164 [wandb_setup.py:_flush():76] Applying login settings: {}
2024-05-16 22:46:09,525 INFO    MainThread:20164 [wandb_init.py:_log_setup():520] Logging user logs to c:\Users\zimmer\Desktop\AVANTECH\deep-sign\Training\wandb\run-20240516_224609-4rx3h718\logs\debug.log
2024-05-16 22:46:09,525 INFO    MainThread:20164 [wandb_init.py:_log_setup():521] Logging internal logs to c:\Users\zimmer\Desktop\AVANTECH\deep-sign\Training\wandb\run-20240516_224609-4rx3h718\logs\debug-internal.log
2024-05-16 22:46:09,525 INFO    MainThread:20164 [wandb_init.py:init():560] calling init triggers
2024-05-16 22:46:09,526 INFO    MainThread:20164 [wandb_init.py:init():567] wandb.init called with sweep_config: {}
config: {}
2024-05-16 22:46:09,526 INFO    MainThread:20164 [wandb_init.py:init():610] starting backend
2024-05-16 22:46:09,526 INFO    MainThread:20164 [wandb_init.py:init():614] setting up manager
2024-05-16 22:46:09,529 INFO    MainThread:20164 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=spawn, using: spawn
2024-05-16 22:46:09,531 INFO    MainThread:20164 [wandb_init.py:init():622] backend started and connected
2024-05-16 22:46:09,537 INFO    MainThread:20164 [wandb_run.py:_label_probe_notebook():1328] probe notebook
2024-05-16 22:46:09,538 INFO    MainThread:20164 [wandb_run.py:_label_probe_notebook():1338] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2024-05-16 22:46:09,538 INFO    MainThread:20164 [wandb_init.py:init():711] updated telemetry
2024-05-16 22:46:09,583 INFO    MainThread:20164 [wandb_init.py:init():744] communicating run to backend with 90.0 second timeout
2024-05-16 22:47:40,202 ERROR   MainThread:20164 [wandb_init.py:init():770] encountered error: Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
2024-05-16 22:47:40,203 ERROR   MainThread:20164 [wandb_init.py:init():1174] error in wandb.init()
Traceback (most recent call last):
  File "c:\Users\zimmer\anaconda3\envs\win_deepsign\lib\site-packages\wandb\sdk\wandb_init.py", line 1164, in init
    return wi.init()
  File "c:\Users\zimmer\anaconda3\envs\win_deepsign\lib\site-packages\wandb\sdk\wandb_init.py", line 776, in init
    raise error
wandb.errors.CommError: Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
2024-05-16 22:47:47,218 WARNING MsgRouterThr:20164 [router.py:message_loop():77] message_loop has been closed
2024-05-16 22:52:41,192 INFO    MainThread:20164 [wandb_settings.py:_apply_login():1895] Applying login settings: {}
2024-05-16 22:52:41,211 INFO    MainThread:20164 [wandb_setup.py:_flush():76] Current SDK version is 0.17.0
2024-05-16 22:52:41,211 INFO    MainThread:20164 [wandb_setup.py:_flush():76] Configure stats pid to 20164
2024-05-16 22:52:41,212 INFO    MainThread:20164 [wandb_setup.py:_flush():76] Loading settings from C:\Users\zimmer\.config\wandb\settings
2024-05-16 22:52:41,212 INFO    MainThread:20164 [wandb_setup.py:_flush():76] Loading settings from c:\Users\zimmer\Desktop\AVANTECH\deep-sign\Training\wandb\settings
2024-05-16 22:52:41,212 INFO    MainThread:20164 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-05-16 22:52:41,213 INFO    MainThread:20164 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-05-16 22:52:41,213 INFO    MainThread:20164 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-05-16 22:52:41,213 INFO    MainThread:20164 [wandb_setup.py:_flush():76] Applying login settings: {}
2024-05-16 22:52:41,215 INFO    MainThread:20164 [wandb_init.py:_log_setup():520] Logging user logs to c:\Users\zimmer\Desktop\AVANTECH\deep-sign\Training\wandb\run-20240516_225241-uhc529nu\logs\debug.log
2024-05-16 22:52:41,215 INFO    MainThread:20164 [wandb_init.py:_log_setup():521] Logging internal logs to c:\Users\zimmer\Desktop\AVANTECH\deep-sign\Training\wandb\run-20240516_225241-uhc529nu\logs\debug-internal.log
2024-05-16 22:52:41,216 INFO    MainThread:20164 [wandb_init.py:init():560] calling init triggers
2024-05-16 22:52:41,216 INFO    MainThread:20164 [wandb_init.py:init():567] wandb.init called with sweep_config: {}
config: {}
2024-05-16 22:52:41,217 INFO    MainThread:20164 [wandb_init.py:init():610] starting backend
2024-05-16 22:52:41,217 INFO    MainThread:20164 [wandb_init.py:init():614] setting up manager
2024-05-16 22:52:41,222 INFO    MainThread:20164 [wandb_init.py:init():622] backend started and connected
2024-05-16 22:52:41,227 INFO    MainThread:20164 [wandb_run.py:_label_probe_notebook():1328] probe notebook
2024-05-16 22:52:41,227 INFO    MainThread:20164 [wandb_run.py:_label_probe_notebook():1338] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2024-05-16 22:52:41,228 INFO    MainThread:20164 [wandb_init.py:init():711] updated telemetry
2024-05-16 22:52:41,279 INFO    MainThread:20164 [wandb_init.py:init():744] communicating run to backend with 90.0 second timeout
2024-05-16 22:54:11,996 ERROR   MainThread:20164 [wandb_init.py:init():770] encountered error: Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
2024-05-16 22:54:11,997 ERROR   MainThread:20164 [wandb_init.py:init():1174] error in wandb.init()
Traceback (most recent call last):
  File "c:\Users\zimmer\anaconda3\envs\win_deepsign\lib\site-packages\wandb\sdk\wandb_init.py", line 1164, in init
    return wi.init()
  File "c:\Users\zimmer\anaconda3\envs\win_deepsign\lib\site-packages\wandb\sdk\wandb_init.py", line 776, in init
    raise error
wandb.errors.CommError: Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
2024-05-16 22:55:20,946 INFO    MainThread:20164 [wandb_settings.py:_apply_login():1895] Applying login settings: {}
2024-05-16 22:55:20,962 INFO    MainThread:20164 [wandb_setup.py:_flush():76] Current SDK version is 0.17.0
2024-05-16 22:55:20,963 INFO    MainThread:20164 [wandb_setup.py:_flush():76] Configure stats pid to 20164
2024-05-16 22:55:20,963 INFO    MainThread:20164 [wandb_setup.py:_flush():76] Loading settings from C:\Users\zimmer\.config\wandb\settings
2024-05-16 22:55:20,964 INFO    MainThread:20164 [wandb_setup.py:_flush():76] Loading settings from c:\Users\zimmer\Desktop\AVANTECH\deep-sign\Training\wandb\settings
2024-05-16 22:55:20,964 INFO    MainThread:20164 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-05-16 22:55:20,967 INFO    MainThread:20164 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-05-16 22:55:20,968 INFO    MainThread:20164 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-05-16 22:55:20,969 INFO    MainThread:20164 [wandb_setup.py:_flush():76] Applying login settings: {}
2024-05-16 22:55:20,970 INFO    MainThread:20164 [wandb_init.py:_log_setup():520] Logging user logs to c:\Users\zimmer\Desktop\AVANTECH\deep-sign\Training\wandb\run-20240516_225520-7gj6l6gy\logs\debug.log
2024-05-16 22:55:20,970 INFO    MainThread:20164 [wandb_init.py:_log_setup():521] Logging internal logs to c:\Users\zimmer\Desktop\AVANTECH\deep-sign\Training\wandb\run-20240516_225520-7gj6l6gy\logs\debug-internal.log
2024-05-16 22:55:20,971 INFO    MainThread:20164 [wandb_init.py:init():560] calling init triggers
2024-05-16 22:55:20,972 INFO    MainThread:20164 [wandb_init.py:init():567] wandb.init called with sweep_config: {}
config: {}
2024-05-16 22:55:20,973 INFO    MainThread:20164 [wandb_init.py:init():610] starting backend
2024-05-16 22:55:20,973 INFO    MainThread:20164 [wandb_init.py:init():614] setting up manager
2024-05-16 22:55:20,978 INFO    MainThread:20164 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=spawn, using: spawn
2024-05-16 22:55:20,987 INFO    MainThread:20164 [wandb_init.py:init():622] backend started and connected
2024-05-16 22:55:20,993 INFO    MainThread:20164 [wandb_run.py:_label_probe_notebook():1328] probe notebook
2024-05-16 22:55:20,993 INFO    MainThread:20164 [wandb_run.py:_label_probe_notebook():1338] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2024-05-16 22:55:20,993 INFO    MainThread:20164 [wandb_init.py:init():711] updated telemetry
2024-05-16 22:55:21,056 INFO    MainThread:20164 [wandb_init.py:init():744] communicating run to backend with 90.0 second timeout
2024-05-16 22:56:51,651 ERROR   MainThread:20164 [wandb_init.py:init():770] encountered error: Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
2024-05-16 22:56:51,652 ERROR   MainThread:20164 [wandb_init.py:init():1174] error in wandb.init()
Traceback (most recent call last):
  File "c:\Users\zimmer\anaconda3\envs\win_deepsign\lib\site-packages\wandb\sdk\wandb_init.py", line 1164, in init
    return wi.init()
  File "c:\Users\zimmer\anaconda3\envs\win_deepsign\lib\site-packages\wandb\sdk\wandb_init.py", line 776, in init
    raise error
wandb.errors.CommError: Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
2024-05-16 22:57:28,528 INFO    MainThread:20164 [wandb_settings.py:_apply_login():1895] Applying login settings: {}
2024-05-16 22:57:28,540 INFO    MainThread:20164 [wandb_setup.py:_flush():76] Current SDK version is 0.17.0
2024-05-16 22:57:28,541 INFO    MainThread:20164 [wandb_setup.py:_flush():76] Configure stats pid to 20164
2024-05-16 22:57:28,541 INFO    MainThread:20164 [wandb_setup.py:_flush():76] Loading settings from C:\Users\zimmer\.config\wandb\settings
2024-05-16 22:57:28,542 INFO    MainThread:20164 [wandb_setup.py:_flush():76] Loading settings from c:\Users\zimmer\Desktop\AVANTECH\deep-sign\Training\wandb\settings
2024-05-16 22:57:28,542 INFO    MainThread:20164 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-05-16 22:57:28,542 INFO    MainThread:20164 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-05-16 22:57:28,543 INFO    MainThread:20164 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-05-16 22:57:28,543 INFO    MainThread:20164 [wandb_setup.py:_flush():76] Applying login settings: {}
2024-05-16 22:57:28,543 INFO    MainThread:20164 [wandb_init.py:_log_setup():520] Logging user logs to c:\Users\zimmer\Desktop\AVANTECH\deep-sign\Training\wandb\run-20240516_225728-fb6hnlkk\logs\debug.log
2024-05-16 22:57:28,543 INFO    MainThread:20164 [wandb_init.py:_log_setup():521] Logging internal logs to c:\Users\zimmer\Desktop\AVANTECH\deep-sign\Training\wandb\run-20240516_225728-fb6hnlkk\logs\debug-internal.log
2024-05-16 22:57:28,543 INFO    MainThread:20164 [wandb_init.py:init():560] calling init triggers
2024-05-16 22:57:28,545 INFO    MainThread:20164 [wandb_init.py:init():567] wandb.init called with sweep_config: {}
config: {}
2024-05-16 22:57:28,545 INFO    MainThread:20164 [wandb_init.py:init():610] starting backend
2024-05-16 22:57:28,545 INFO    MainThread:20164 [wandb_init.py:init():614] setting up manager
2024-05-16 22:57:28,547 INFO    MainThread:20164 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=spawn, using: spawn
2024-05-16 22:57:28,554 INFO    MainThread:20164 [wandb_init.py:init():622] backend started and connected
2024-05-16 22:57:28,560 INFO    MainThread:20164 [wandb_run.py:_label_probe_notebook():1328] probe notebook
2024-05-16 22:57:28,560 INFO    MainThread:20164 [wandb_run.py:_label_probe_notebook():1338] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2024-05-16 22:57:28,560 INFO    MainThread:20164 [wandb_init.py:init():711] updated telemetry
2024-05-16 22:57:28,610 INFO    MainThread:20164 [wandb_init.py:init():744] communicating run to backend with 90.0 second timeout
2024-05-16 22:58:59,147 ERROR   MainThread:20164 [wandb_init.py:init():770] encountered error: Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
2024-05-16 22:58:59,147 ERROR   MainThread:20164 [wandb_init.py:init():1174] error in wandb.init()
Traceback (most recent call last):
  File "c:\Users\zimmer\anaconda3\envs\win_deepsign\lib\site-packages\wandb\sdk\wandb_init.py", line 1164, in init
    return wi.init()
  File "c:\Users\zimmer\anaconda3\envs\win_deepsign\lib\site-packages\wandb\sdk\wandb_init.py", line 776, in init
    raise error
wandb.errors.CommError: Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
